export enum tagTypes {
  user = "user",
  register = "register",
  users = "users",
  singleUser = "singleUser",
  profile = "profile",
  updateProfile = "updateProfile",
  collections = "collections",
  collectionsSummary = "collectionsSummary",
  contributeRates = "contributeRates",
  createContributeRates = "createContributeRates",
  delSubRates = "delSubRates",
  singleCollection = "singleCollection",
  singleContributeRates = "singleContributeRates",
  updateSingleCollection = "updateSingleCollection",
  deleteSingleCollection = "deleteSingleCollection",
  cheque = "cheque",
  expenses = "expenses",
  expenseFilter = "expenseFilter",
  draftBill = "draftBill",
  draftSingleBill = "draftSingleBill",
  deleteSingleBill = "deleteSingleBill",
  updateSingleBill = "updateSingleBill",
  fiscalYear = "fiscalYear",
  sentBacks = "sentBacks",
  cashBook = "cashBook",
  singleCashBook = "singleCashBook",
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.register,
  tagTypes.users,
  tagTypes.singleUser,
  tagTypes.profile,
  tagTypes.updateProfile,
  tagTypes.collections,
  tagTypes.collectionsSummary,
  tagTypes.singleCollection,
  tagTypes.updateSingleCollection,
  tagTypes.deleteSingleCollection,
  tagTypes.expenseFilter,
  tagTypes.expenses,
  tagTypes.user,
  tagTypes.cheque,
  tagTypes.draftBill,
  tagTypes.sentBacks,
  tagTypes.draftSingleBill,
  tagTypes.deleteSingleBill,
  tagTypes.updateSingleBill,
  tagTypes.fiscalYear,
  tagTypes.cashBook,
  tagTypes.singleCashBook,
  tagTypes.contributeRates,
  tagTypes.singleContributeRates,
  tagTypes.createContributeRates,
  tagTypes.delSubRates,
];
