export enum tagTypes {
  user = "user",
  users = "users",
  singleUser = "singleUser",
  profile = "profile",
  updateProfile = "updateProfile",
  collections = "collections",
  singleCollection = "singleCollection",
  updateSingleCollection = "updateSingleCollection",
  deleteSingleCollection = "deleteSingleCollection",
  cheque = "cheque",
  expenses = "expenses",
  expenseFilter = "expenseFilter",
  draftBill = "draftBill",
  draftSingleBill = "draftSingleBill",
  deleteSingleBill = "deleteSingleBill",
  updateSingleBill = "updateSingleBill",
  fiscalYear = "fiscalYear",
  sentBacks = "sentBacks",
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.users,
  tagTypes.singleUser,
  tagTypes.profile,
  tagTypes.updateProfile,
  tagTypes.collections,
  tagTypes.singleCollection,
  tagTypes.updateSingleCollection,
  tagTypes.deleteSingleCollection,
  tagTypes.expenseFilter,
  tagTypes.expenses,
  tagTypes.user,
  tagTypes.cheque,
  tagTypes.draftBill,
  tagTypes.sentBacks,
  tagTypes.draftSingleBill,
  tagTypes.deleteSingleBill,
  tagTypes.updateSingleBill,
  tagTypes.fiscalYear,
];
